name: Cleanup Repository

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Clone other repository
      run: git clone https://github.com/Gordo2105/sitentfy.git
      
    - name: Delete non-HTML files
      run: |
        find other-repo -type f ! -name "*.html" -delete
        cd other-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Delete non-HTML files"
        git push origin HEAD:main
        
